# Generated by Django 4.1.7 on 2023-03-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_site', '0012_listing_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='buysell',
            field=models.CharField(default='Buying', max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment',
            field=models.CharField(default='DogeCoin', max_length=255),
        ),
    ]
