# Generated by Django 4.1.7 on 2023-04-26 23:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce_site', '0015_profilel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profilel',
            new_name='Profile',
        ),
    ]
