# Generated by Django 4.1.7 on 2023-04-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_site', '0019_message_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='buyorsell',
            field=models.CharField(default='sell', max_length=5),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('listings', models.ManyToManyField(to='ecommerce_site.listing')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='tags',
            field=models.ManyToManyField(to='ecommerce_site.tag'),
        ),
    ]
