# Generated by Django 4.1.7 on 2023-05-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_site', '0020_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='buyorsell',
            field=models.CharField(default='sell', max_length=5),
        ),
    ]
