# Generated by Django 4.1.7 on 2023-04-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_site', '0021_remove_listing_tags_listing_tag1_listing_tag2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='tag1',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='tag3',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='tag4',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='tag5',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='listings',
        ),
        migrations.AddField(
            model_name='listing',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='ecommerce_site.tag'),
        ),
    ]
